
class Constants:
    PROGRESS_MEMORY_DIRECTORY = "./q_learning_taxi_env_agent/progress_memory/"
    PLAYER_VIDEOS_DIRECTORY = "./q_learning_taxi_env_agent/player_videos/"
    STATISTICS_TOTAL_EPISODE_COUNT = "total_episodes_count"
    STATISTICS_LATEST_EPISODE_COUNT = "latest_episode_count"
    CHECKPOINT_NETWORK_STATE_DICT = "network_state_dict"
    CHECKPOINT_OPTIMIZER_STATE_DICT = "optimizer_state_dict"
    STATISTICS_RETURN_QUEUE = "return_queue"
    STATISTICS_LENGTH_QUEUE = "length_queue"
    STATISTICS_TRAINING_ERROR = "training_error"
    PLAYER_NAME_PREFIX = "player"
    ENVIRONMENT_ID_TAXI_V3 = "Taxi-v3"
    ENVIRONMENT_LUNAR_LANDER_V3 = "LunarLander-v3"
    ENVIRONMENT_ALE_MS_PACMAN_DETERMINISTIC_V4 = "MsPacmanDeterministic-v4"
    ENVIRONMENT_ALE_BREAKOUT_NO_FRAMESKIP_V4 = "BreakoutNoFrameskip-v4"