LEARNING_RATE = 0.001
DISCOUNT_FACTOR = 0.99
N_TRAINING_EPISODES = 1_0
N_PLAYING_EPISODES = 10
START_EPSILON = 1.0
EPSILON_DECAY = START_EPSILON / (N_TRAINING_EPISODES / 2)
FINAL_EPSILON = 0.05
SEED = 42